In [1]:
import torch
from torch import nn

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
df=pd.read_csv("quikr_car.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [5]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [6]:
df["Price"].value_counts()

Price
Ask For Price    35
2,50,000         17
3,50,000         14
1,80,000         13
4,00,000         12
                 ..
39,999            1
50,500            1
5,10,000          1
8,60,000          1
5,00,001          1
Name: count, Length: 274, dtype: int64

In [7]:
df["kms_driven"].value_counts()

kms_driven
45,000 kms      30
35,000 kms      30
55,000 kms      25
50,000 kms      23
20,000 kms      22
                ..
1,46,000 kms     1
1,00,800 kms     1
2,100 kms        1
2,500 kms        1
1,32,000 kms     1
Name: count, Length: 258, dtype: int64

In [8]:
df["year"].value_counts()

year
2015    117
2014     94
2013     94
2016     76
2012     75
       ...
cab       1
t xe      1
EV2       1
r...      1
zest      1
Name: count, Length: 61, dtype: int64

In [9]:
import numpy as np

df['Price'] = df['Price'].replace('Ask For Price', np.nan)

df['Price'] = (
    df['Price']
    .astype(str)
    .str.replace(',', '', regex=False)
)

df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

df['kms_driven'] = (
    df['kms_driven']
    .astype(str)
    .str.replace(',', '', regex=False)     
    .str.replace('kms', '', regex=False)   
    .str.strip()                            
)

df['kms_driven'] = pd.to_numeric(df['kms_driven'], errors='coerce')

df['year'] = pd.to_numeric(df['year'], errors='coerce')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        842 non-null    float64
 3   Price       857 non-null    float64
 4   kms_driven  838 non-null    float64
 5   fuel_type   837 non-null    str
dtypes: float64(3), str(3)
memory usage: 41.9 KB

In [11]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018.0,NaN,22000.0,Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel

In [12]:
df.dropna(inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    str
 1   company     816 non-null    str
 2   year        816 non-null    float64
 3   Price       816 non-null    float64
 4   kms_driven  816 non-null    float64
 5   fuel_type   816 non-null    str
dtypes: float64(3), str(3)
memory usage: 44.6 KB

In [14]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel
6,Ford Figo,Ford,2012.0,175000.0,41000.0,Diesel

In [15]:
df.drop(columns=['name'], inplace=True)

In [16]:
from sklearn.preprocessing import LabelEncoder


TARGET_COL = "Price"
BATCH_SIZE = 64
EPOCHS = 7
learning_rates = [0.1, 0.01, 0.001, 0.0001, 0.00001]

x = df.drop(columns=[TARGET_COL]) # Features

y = df[TARGET_COL] # Target

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Encoding categorical features using LabelEncoder
def encode_train(df):
    df = df.copy()
    encoders = {}
    for col in df.columns:
        if not pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].astype(str)
            encoder = LabelEncoder()
            df[col] = encoder.fit_transform(df[col])
            encoders[col] = encoder
    return df, encoders

def encode_test(df, encoders):
    df = df.copy()
    for col, encoder in encoders.items():
        df[col] = df[col].astype(str)
        known = set(encoder.classes_)
        df[col] = df[col].apply(lambda x: encoder.transform([x])[0] if x in known else -1)
    return df

encoded_xtrain, encoders = encode_train(x_train)   # train
encoded_xtest = encode_test(x_test, encoders)       # test

# SML

In [17]:
x__train = encoded_xtrain.copy()
x__test = encoded_xtest.copy()
y__train = y_train.copy()
y__test = y_test.copy()

In [18]:
x__train.info()

<class 'pandas.DataFrame'>
Index: 652 entries, 472 to 106
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   company     652 non-null    int64
 1   year        652 non-null    float64
 2   kms_driven  652 non-null    float64
 3   fuel_type   652 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 25.5 KB

In [19]:
y__train.info()

<class 'pandas.Series'>
Index: 652 entries, 472 to 106
Series name: Price
Non-Null Count  Dtype
--------------  -----
652 non-null    float64
dtypes: float64(1)
memory usage: 10.2 KB

In [20]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
def scale_train(df):
    scalers = {}

    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            scaler = MinMaxScaler()
            df[col] = scaler.fit_transform(df[[col]])
            scalers[col] = scaler
    return df, scalers

def scale_test(df, scalers):
    for col in df.columns:
        if col in scalers:
            scaler = scalers[col]
            df[col] = scaler.transform(df[[col]])
    return df

scaled__xtrain, scalers = scale_train(x__train)   # train
scaled__xtest = scale_test(x__test, scalers)      # test

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

lr_model = RandomForestRegressor()
lr_model.fit(scaled__xtrain, y__train)
y_pred = lr_model.predict(scaled__xtest)

print("R2 score of Random Forest model on test data:", r2_score(y__test, y_pred))

R2 score of Random Forest model on test data: 0.18449047078987968

In [22]:

# Pandas to Numpy
x_train = encoded_xtrain.to_numpy()
x_test = encoded_xtest.to_numpy()
y_train_arr = y_train.to_numpy().reshape(-1, 1)
y_test_arr = y_test.to_numpy().reshape(-1, 1)

# Scaling the features and target variable
from sklearn.preprocessing import StandardScaler

x_scaler = MinMaxScaler()
scaled_xtrain = x_scaler.fit_transform(encoded_xtrain)
scaled_xtest  = x_scaler.transform(encoded_xtest)

y_scaler = MinMaxScaler()
scaled_ytrain = y_scaler.fit_transform(y_train_arr)
scaled_ytest  = y_scaler.transform(y_test_arr)

# Numpy to Torch Tensor
x_train_tensor = torch.tensor(scaled_xtrain, dtype=torch.float32)
x_test_tensor = torch.tensor(scaled_xtest, dtype=torch.float32)

y_train_tensor = torch.tensor(scaled_ytrain, dtype=torch.float32)
y_test_tensor = torch.tensor(scaled_ytest, dtype=torch.float32)

In [23]:
print("X Train Tensor:", x_train_tensor.shape)
print("Y Train Tensor:", y_train_tensor.shape)
print("X Test Tensor:", x_test_tensor.shape)
print("Y Test Tensor:", y_test_tensor.shape)

X Train Tensor: torch.Size([652, 4])
Y Train Tensor: torch.Size([652, 1])
X Test Tensor: torch.Size([164, 4])
Y Test Tensor: torch.Size([164, 1])

In [24]:
# TensorDataset and DataLoader
from torch.utils.data import TensorDataset, DataLoader, random_split

dataset = TensorDataset(
    x_train_tensor,
    y_train_tensor
)

train_size = int(0.9 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size]
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_dataset = TensorDataset(
    x_test_tensor,
    y_test_tensor
)
test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

In [25]:
train_dataset[0]

(tensor([0.5652, 0.5000, 0.1400, 0.0000]), tensor([0.0749]))

In [26]:
train_loader

In [27]:
# Model
from torch import nn, optim



torch.manual_seed(0) # random seed for reproducibility
input_dim = x_train_tensor.shape[1] # features
hidden_dim = 64 # hidden units
output_dim = 1 # output units


def train_model(ALPHA):
    model = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),   #Intput
        nn.ReLU(),   #Hidden 
        nn.Linear(hidden_dim, output_dim)   #Output
    )
    loss_fn = nn.MSELoss()   
    opt = optim.Adam(model.parameters(), lr=ALPHA)
    best_val_loss = float("inf")
    best_val_r2 = float("-inf")

    for epoch in range(1, EPOCHS + 1):
        model.train() 
        total_loss = 0.0  

        for bx, by in train_loader:
            pred = model(bx) 
            loss = loss_fn(pred, by) 
            opt.zero_grad() 
            loss.backward() 
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step() 
            total_loss += loss.item() 
        train_loss = total_loss / len(train_loader) 

        # Validation
        model.eval()

        total_val_loss = 0.0

        all_preds = []
        all_targets = []

        with torch.no_grad():
            for bx, by in val_loader:

                pred = model(bx)
                loss = loss_fn(pred, by)
                total_val_loss += loss.item()   
                all_preds.extend(pred.squeeze().cpu().numpy())
                all_targets.extend(by.squeeze().cpu().numpy())

        val_loss = total_val_loss / len(val_loader)
        val_r2 = r2_score(all_targets, all_preds)

        print(
            f"LR: {ALPHA} | "
            f"Epoch: {epoch} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val R2: {val_r2:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss

        if best_val_r2 < val_r2:
            best_val_r2 = val_r2

    return best_val_loss, best_val_r2

# Learning rate (experiment)

In [28]:
results = {}

for lr in learning_rates:

    print(f"\n===== Learning Rate: {lr} =====")

    best_val_loss, best_val_r2 = train_model(lr)

    results[lr] = (best_val_loss, best_val_r2)

print(results)

===== Learning Rate: 0.1 =====
LR: 0.1 | Epoch: 1 | Train Loss: 0.2038 | Val Loss: 0.0122 | Val R2: -0.4573
LR: 0.1 | Epoch: 2 | Train Loss: 0.0193 | Val Loss: 0.0096 | Val R2: -0.1191
LR: 0.1 | Epoch: 3 | Train Loss: 0.0201 | Val Loss: 0.0078 | Val R2: -0.0032
LR: 0.1 | Epoch: 4 | Train Loss: 0.0143 | Val Loss: 0.0078 | Val R2: -0.0023
LR: 0.1 | Epoch: 5 | Train Loss: 0.0142 | Val Loss: 0.0079 | Val R2: -0.0012
LR: 0.1 | Epoch: 6 | Train Loss: 0.0143 | Val Loss: 0.0078 | Val R2: -0.0057
LR: 0.1 | Epoch: 7 | Train Loss: 0.0153 | Val Loss: 0.0078 | Val R2: -0.0002

===== Learning Rate: 0.01 =====
LR: 0.01 | Epoch: 1 | Train Loss: 0.0221 | Val Loss: 0.0176 | Val R2: -0.5921
LR: 0.01 | Epoch: 2 | Train Loss: 0.0174 | Val Loss: 0.0080 | Val R2: 0.0154
LR: 0.01 | Epoch: 3 | Train Loss: 0.0136 | Val Loss: 0.0066 | Val R2: 0.0842
LR: 0.01 | Epoch: 4 | Train Loss: 0.0135 | Val Loss: 0.0061 | Val R2: 0.1298
LR: 0.01 | Epoch: 5 | Train Loss: 0.0145 | Val Loss: 0.0062 | Val R2: 0.1355
LR: 0.01 | Epoch: 6 | Train Loss: 0.0120 | Val Loss: 0.0063 | Val R2: 0.0784
LR: 0.01 | Epoch: 7 | Train Loss: 0.0132 | Val Loss: 0.0062 | Val R2: 0.1555

===== Learning Rate: 0.001 =====
LR: 0.001 | Epoch: 1 | Train Loss: 0.0283 | Val Loss: 0.0108 | Val R2: -0.4745
LR: 0.001 | Epoch: 2 | Train Loss: 0.0199 | Val Loss: 0.0104 | Val R2: -0.1764
LR: 0.001 | Epoch: 3 | Train Loss: 0.0171 | Val Loss: 0.0117 | Val R2: -0.0734
LR: 0.001 | Epoch: 4 | Train Loss: 0.0188 | Val Loss: 0.0119 | Val R2: -0.0370
LR: 0.001 | Epoch: 5 | Train Loss: 0.0151 | Val Loss: 0.0109 | Val R2: 0.0059
LR: 0.001 | Epoch: 6 | Train Loss: 0.0140 | Val Loss: 0.0097 | Val R2: 0.0535
LR: 0.001 | Epoch: 7 | Train Loss: 0.0158 | Val Loss: 0.0088 | Val R2: 0.0853

===== Learning Rate: 0.0001 =====
LR: 0.0001 | Epoch: 1 | Train Loss: 0.0156 | Val Loss: 0.0077 | Val R2: -0.0263
LR: 0.0001 | Epoch: 2 | Train Loss: 0.0160 | Val Loss: 0.0074 | Val R2: 0.0211
LR: 0.0001 | Epoch: 3 | Train Loss: 0.0134 | Val Loss: 0.0074 | Val R2: 0.0360
LR: 0.0001 | Epoch: 4 | Train Loss: 0.0134 | Val Loss: 0.0074 | Val R2: 0.0418
LR: 0.0001 | Epoch: 5 | Train Loss: 0.0132 | Val Loss: 0.0075 | Val R2: 0.0447
LR: 0.0001 | Epoch: 6 | Train Loss: 0.0202 | Val Loss: 0.0075 | Val R2: 0.0471
LR: 0.0001 | Epoch: 7 | Train Loss: 0.0135 | Val Loss: 0.0074 | Val R2: 0.0496

===== Learning Rate: 1e-05 =====
LR: 1e-05 | Epoch: 1 | Train Loss: 0.0318 | Val Loss: 0.0298 | Val R2: -1.2770
LR: 1e-05 | Epoch: 2 | Train Loss: 0.0298 | Val Loss: 0.0293 | Val R2: -1.2396
LR: 1e-05 | Epoch: 3 | Train Loss: 0.0337 | Val Loss: 0.0288 | Val R2: -1.2031
LR: 1e-05 | Epoch: 4 | Train Loss: 0.0311 | Val Loss: 0.0283 | Val R2: -1.1669
LR: 1e-05 | Epoch: 5 | Train Loss: 0.0282 | Val Loss: 0.0278 | Val R2: -1.1320
LR: 1e-05 | Epoch: 6 | Train Loss: 0.0292 | Val Loss: 0.0274 | Val R2: -1.0981
LR: 1e-05 | Epoch: 7 | Train Loss: 0.0291 | Val Loss: 0.0269 | Val R2: -1.0651
{0.1: (0.007780581014230847, -0.00018231005419422353), 0.01: (0.006124260253272951, 0.15549200519835615), 0.001: (0.00877416506409645, 0.08529895728928893), 0.0001: (0.007360065705142915, 0.04962768706479159), 1e-05: (0.02689413260668516, -1.0650625290846834)}

In [29]:
results

{0.1: (0.007780581014230847, -0.00018231005419422353),
 0.01: (0.006124260253272951, 0.15549200519835615),
 0.001: (0.00877416506409645, 0.08529895728928893),
 0.0001: (0.007360065705142915, 0.04962768706479159),
 1e-05: (0.02689413260668516, -1.0650625290846834)}

In [30]:
best_lr = max(results, key=lambda lr: results[lr][1])
best_loss, best_r2 = results[best_lr]
print(f"Best Learning Rate (R2): {best_lr}")
print(f"Validation Loss: {best_loss:.4f}")
print(f"Validation R²: {best_r2:.4f}")

best_lr = min(results, key=lambda lr: results[lr][0])
best_loss, best_r2 = results[best_lr]
print(f"Best Learning Rate (Validation loss): {best_lr}")
print(f"Validation Loss: {best_loss:.4f}")
print(f"Validation R²: {best_r2:.4f}")

Best Learning Rate (R2): 0.01
Validation Loss: 0.0061
Validation R²: 0.1555
Best Learning Rate (Validation loss): 0.01
Validation Loss: 0.0061
Validation R²: 0.1555

# Learning Rate (Scheduler)

In [31]:
# Model
from torch import nn, optim



torch.manual_seed(0) # random seed for reproducibility
input_dim = x_train_tensor.shape[1] # features
hidden_dim = 64 # hidden units
output_dim = 1 # output units


def train_model(ALPHA):
    model = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),   #Intput
        nn.ReLU(),   #Hidden 
        nn.Linear(hidden_dim, output_dim)   #Output
    )
    loss_fn = nn.MSELoss()   
    opt = optim.Adam(model.parameters(), lr=ALPHA)
    scheduler = optim.lr_scheduler.StepLR(opt, step_size=10, gamma=0.1)

    best_val_loss = float("inf")
    best_val_r2 = float("-inf")

    for epoch in range(1, EPOCHS + 1):
        model.train() 
        total_loss = 0.0  

        for bx, by in train_loader:
            pred = model(bx) 
            loss = loss_fn(pred, by) 
            opt.zero_grad() 
            loss.backward() 
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step() 
            total_loss += loss.item() 
        train_loss = total_loss / len(train_loader) 

        # Validation
        model.eval()

        total_val_loss = 0.0

        all_preds = []
        all_targets = []

        with torch.no_grad():
            for bx, by in val_loader:

                pred = model(bx)
                loss = loss_fn(pred, by)
                total_val_loss += loss.item()   
                all_preds.extend(pred.squeeze().cpu().numpy())
                all_targets.extend(by.squeeze().cpu().numpy())

        val_loss = total_val_loss / len(val_loader)
        val_r2 = r2_score(all_targets, all_preds)
        scheduler.step(val_loss)

        print(
            f"LR: {opt.param_groups[0]["lr"]} | "
            f"Epoch: {epoch} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val R2: {val_r2:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss

        if best_val_r2 < val_r2:
            best_val_r2 = val_r2

    return best_val_loss, best_val_r2

In [32]:


best_val_loss, best_val_r2 = train_model(0.1)

print("Val loss", best_val_loss)
print("R2", best_val_r2)

LR: 0.1 | Epoch: 1 | Train Loss: 0.2038 | Val Loss: 0.0122 | Val R2: -0.4573
LR: 0.1 | Epoch: 2 | Train Loss: 0.0193 | Val Loss: 0.0096 | Val R2: -0.1191
LR: 0.1 | Epoch: 3 | Train Loss: 0.0201 | Val Loss: 0.0078 | Val R2: -0.0032
LR: 0.1 | Epoch: 4 | Train Loss: 0.0143 | Val Loss: 0.0078 | Val R2: -0.0023
LR: 0.1 | Epoch: 5 | Train Loss: 0.0142 | Val Loss: 0.0079 | Val R2: -0.0012
LR: 0.1 | Epoch: 6 | Train Loss: 0.0143 | Val Loss: 0.0078 | Val R2: -0.0057
LR: 0.1 | Epoch: 7 | Train Loss: 0.0153 | Val Loss: 0.0078 | Val R2: -0.0002
Val loss 0.007780581014230847
R2 -0.00018231005419422353

/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)
/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)
/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)
/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)
/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)
/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)
/var/folders/l4/yvznx4n97gs21nxg5vxxc07r0000gn/T/ipykernel_41988/3922693457.py:58: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  scheduler.step(val_loss)

# Dropout Regularization

In [33]:
# Model
from torch import nn, optim



torch.manual_seed(0) # random seed for reproducibility
input_dim = x_train_tensor.shape[1] # features
hidden_dim = 64 # hidden units
output_dim = 1 # output units


def train_model(ALPHA):
    model = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),   #Intput
        nn.ReLU(),   #Hidden 
        nn.Dropout(p=0.2), #Dropout
        nn.Linear(hidden_dim, output_dim)   #Output
    )
    loss_fn = nn.MSELoss()   
    opt = optim.Adam(model.parameters(), lr=ALPHA)
    best_val_loss = float("inf")
    best_val_r2 = float("-inf")

    for epoch in range(1, EPOCHS + 1):
        model.train() 
        total_loss = 0.0  

        for bx, by in train_loader:
            pred = model(bx) 
            loss = loss_fn(pred, by) 
            opt.zero_grad() 
            loss.backward() 
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step() 
            total_loss += loss.item() 
        train_loss = total_loss / len(train_loader) 

        # Validation
        model.eval()

        total_val_loss = 0.0

        all_preds = []
        all_targets = []

        with torch.no_grad():
            for bx, by in val_loader:

                pred = model(bx)
                loss = loss_fn(pred, by)
                total_val_loss += loss.item()   
                all_preds.extend(pred.squeeze().cpu().numpy())
                all_targets.extend(by.squeeze().cpu().numpy())

        val_loss = total_val_loss / len(val_loader)
        val_r2 = r2_score(all_targets, all_preds)

        print(
            f"LR: {ALPHA} | "
            f"Epoch: {epoch} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val R2: {val_r2:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss

        if best_val_r2 < val_r2:
            best_val_r2 = val_r2

    return best_val_loss, best_val_r2

In [34]:
best_val_loss_dropout, best_val_r2_dropout = train_model(0.001)

LR: 0.001 | Epoch: 1 | Train Loss: 0.1519 | Val Loss: 0.0822 | Val R2: -6.3854
LR: 0.001 | Epoch: 2 | Train Loss: 0.0665 | Val Loss: 0.0207 | Val R2: -1.5088
LR: 0.001 | Epoch: 3 | Train Loss: 0.0398 | Val Loss: 0.0103 | Val R2: -0.5051
LR: 0.001 | Epoch: 4 | Train Loss: 0.0264 | Val Loss: 0.0108 | Val R2: -0.3452
LR: 0.001 | Epoch: 5 | Train Loss: 0.0264 | Val Loss: 0.0103 | Val R2: -0.1533
LR: 0.001 | Epoch: 6 | Train Loss: 0.0210 | Val Loss: 0.0109 | Val R2: -0.0959
LR: 0.001 | Epoch: 7 | Train Loss: 0.0199 | Val Loss: 0.0110 | Val R2: -0.0656

In [35]:
best_val_loss_dropout

0.01025580195710063

# L2 regularization

In [36]:
# Model
from torch import nn, optim



torch.manual_seed(0) # random seed for reproducibility
input_dim = x_train_tensor.shape[1] # features
hidden_dim = 64 # hidden units
output_dim = 1 # output units


def train_model(ALPHA):
    model = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),   #Intput
        nn.ReLU(),   #Hidden 
        nn.Linear(hidden_dim, output_dim)   #Output
    )
    loss_fn = nn.MSELoss()   
    opt = optim.Adam(model.parameters(), lr=ALPHA, weight_decay=1e-4)
    best_val_loss = float("inf")
    best_val_r2 = float("-inf")

    for epoch in range(1, EPOCHS + 1):
        model.train() 
        total_loss = 0.0  

        for bx, by in train_loader:
            pred = model(bx) 
            loss = loss_fn(pred, by) 
            opt.zero_grad() 
            loss.backward() 
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step() 
            total_loss += loss.item() 
        train_loss = total_loss / len(train_loader) 

        # Validation
        model.eval()

        total_val_loss = 0.0

        all_preds = []
        all_targets = []

        with torch.no_grad():
            for bx, by in val_loader:

                pred = model(bx)
                loss = loss_fn(pred, by)
                total_val_loss += loss.item()   
                all_preds.extend(pred.squeeze().cpu().numpy())
                all_targets.extend(by.squeeze().cpu().numpy())

        val_loss = total_val_loss / len(val_loader)
        val_r2 = r2_score(all_targets, all_preds)

        print(
            f"LR: {ALPHA} | "
            f"Epoch: {epoch} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val R2: {val_r2:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss

        if best_val_r2 < val_r2:
            best_val_r2 = val_r2

    return best_val_loss, best_val_r2

In [37]:
best_val_loss_l2, best_val_r2_l2 = train_model(0.001)

LR: 0.001 | Epoch: 1 | Train Loss: 0.1462 | Val Loss: 0.0818 | Val R2: -6.3605
LR: 0.001 | Epoch: 2 | Train Loss: 0.0597 | Val Loss: 0.0208 | Val R2: -1.5211
LR: 0.001 | Epoch: 3 | Train Loss: 0.0311 | Val Loss: 0.0103 | Val R2: -0.5122
LR: 0.001 | Epoch: 4 | Train Loss: 0.0214 | Val Loss: 0.0104 | Val R2: -0.3344
LR: 0.001 | Epoch: 5 | Train Loss: 0.0186 | Val Loss: 0.0100 | Val R2: -0.1580
LR: 0.001 | Epoch: 6 | Train Loss: 0.0163 | Val Loss: 0.0104 | Val R2: -0.0841
LR: 0.001 | Epoch: 7 | Train Loss: 0.0157 | Val Loss: 0.0103 | Val R2: -0.0366

In [38]:
best_val_loss_l2

0.010028062853962183

# BatchNorm regularization

In [39]:
# Model
from torch import nn, optim



torch.manual_seed(0) # random seed for reproducibility
input_dim = x_train_tensor.shape[1] # features
hidden_dim = 64 # hidden units
output_dim = 1 # output units


def train_model(ALPHA):
    model = nn.Sequential(
        nn.Linear(input_dim, hidden_dim),   #Intput
        nn.BatchNorm1d(64), #BatchNorm
        nn.ReLU(),   #Hidden 
        nn.Linear(hidden_dim, output_dim)   #Output
    )
    loss_fn = nn.MSELoss()   
    opt = optim.Adam(model.parameters(), lr=ALPHA, weight_decay=1e-4)
    best_val_loss = float("inf")
    best_val_r2 = float("-inf")

    for epoch in range(1, EPOCHS + 1):
        model.train() 
        total_loss = 0.0  

        for bx, by in train_loader:
            pred = model(bx) 
            loss = loss_fn(pred, by) 
            opt.zero_grad() 
            loss.backward() 
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step() 
            total_loss += loss.item() 
        train_loss = total_loss / len(train_loader) 

        # Validation
        model.eval()

        total_val_loss = 0.0

        all_preds = []
        all_targets = []

        with torch.no_grad():
            for bx, by in val_loader:

                pred = model(bx)
                loss = loss_fn(pred, by)
                total_val_loss += loss.item()   
                all_preds.extend(pred.squeeze().cpu().numpy())
                all_targets.extend(by.squeeze().cpu().numpy())

        val_loss = total_val_loss / len(val_loader)
        val_r2 = r2_score(all_targets, all_preds)

        print(
            f"LR: {ALPHA} | "
            f"Epoch: {epoch} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val R2: {val_r2:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss

        if best_val_r2 < val_r2:
            best_val_r2 = val_r2

    return best_val_loss, best_val_r2

In [40]:
best_val_loss_batchnorm, best_val_r2_batchnorm = train_model(0.001)

LR: 0.001 | Epoch: 1 | Train Loss: 0.2831 | Val Loss: 0.0410 | Val R2: -3.2735
LR: 0.001 | Epoch: 2 | Train Loss: 0.1045 | Val Loss: 0.0136 | Val R2: -1.0908
LR: 0.001 | Epoch: 3 | Train Loss: 0.0481 | Val Loss: 0.0180 | Val R2: -0.9826
LR: 0.001 | Epoch: 4 | Train Loss: 0.0272 | Val Loss: 0.0172 | Val R2: -0.8464
LR: 0.001 | Epoch: 5 | Train Loss: 0.0174 | Val Loss: 0.0116 | Val R2: -0.3030
LR: 0.001 | Epoch: 6 | Train Loss: 0.0138 | Val Loss: 0.0103 | Val R2: -0.0971
LR: 0.001 | Epoch: 7 | Train Loss: 0.0155 | Val Loss: 0.0087 | Val R2: -0.0092

In [41]:
best_val_loss_batchnorm

0.008716875221580267

In [42]:
import pandas as pd

results = {
    "BatchNorm": [
        best_val_loss_batchnorm,
        best_val_r2_batchnorm
    ],
    "L2": [
        best_val_loss_l2,
        best_val_r2_l2
    ],
    "Dropout": [
        best_val_loss_dropout,
        best_val_r2_dropout
    ]
}

df = pd.DataFrame(
    results,
    index=["Val Loss", "Val R2"]
).T

print(df)

           Val Loss    Val R2
BatchNorm  0.008717 -0.009188
L2         0.010028 -0.036572
Dropout    0.010256 -0.065562